//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SahaDetay
    {
        public int SahaDetayId { get; set; }
        public Nullable<int> SahaIdFk { get; set; }
        public string CimTuru { get; set; }
        public string İkram { get; set; }
        public string Dus { get; set; }
        public string SoyunmaOdasi { get; set; }
        public string Otopark { get; set; }
    
        public virtual Saha Saha { get; set; }
    }
}
